version: '3.7'

services:
  pn-server:
    image: pnlab-server:1.0.0
    build:
      context: ..
      dockerfile: server.Dockerfile
    depends_on:
      - db
      - mq
  pn-python:
    image: pnlab-service:1.0.0
    build:
      context: ..
      dockerfile: python.Dockerfile
    depends_on:
      - db
      - mq
  db:
    image: mongo:latest
    container_name: pn-db
  mq:
    image: rabbitmq:latest
    container_name: pn-mq
networks:
volume: