version: '3.7'

services:
  pn-server:
    image: pnlab-server:1.0.5
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    ports:
      - '3005:3000'
    depends_on:
      - db
      - mq
    volumes:
      - 'temp:/var/pnlab/temp'
    networks:
      - pn-net
    environment:
      - MONGO_DB_ADDRESS=db
      - RABBIT_MQ_ADDRESS=mq
  pn-service:
    image: pnlab-service:1.0.3
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    depends_on:
      - db
      - mq
    volumes:
      - 'temp:/var/pnlab/temp'
    networks:
      - pn-net
    environment:
      - MONGO_DB_ADDRESS=db
      - RABBIT_MQ_ADDRESS=mq
  db:
    image: mongo:pnlab
    build:
      context: ..
      dockerfile: docker/mongo.Dockerfile
    networks:
      - pn-net
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - NEW_ENV=test
  mq:
    image: rabbitmq:latest
    networks:
      - pn-net
networks:
  pn-net:
volumes:
  temp:
