version: '3.7'

services:
  pn-server:
    image: pnlab-server:1.0.4
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    ports:
      - '3005:3000'
    depends_on:
      - db
      - mq
    volumes:
      - 'temp:/var/pnlab/temp'
    networks:
      - pn-net
    environment:
      - MONGO_DB_ADDRESS=pn-db
      - RABBIT_MQ_ADDRESS=pn-mq
  pn-service:
    image: pnlab-service:1.0.1
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    depends_on:
      - db
      - mq
    volumes:
      - 'temp:/var/pnlab/temp'
    networks:
      - pn-net
    environment:
      - MONGO_DB_ADDRESS=pn-db
      - RABBIT_MQ_ADDRESS=pn-mq
  db:
    image: mongo:pnlab
    container_name: pn-db
    build:
      context: ..
      dockerfile: docker/mongo.Dockerfile
    networks:
      - pn-net
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=pn
  mq:
    image: rabbitmq:latest
    container_name: pn-mq
    networks:
      - pn-net
networks:
  pn-net:
volumes:
  temp:
